server:
  port: 8081

Spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:mcq_quiz_db
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: create

  h2:
    console:
      enabled: true
